### ISSUE TITLE
Make next exercise more visible during preparation

### ISSUE THREAD

**Issue by jorgman1** [oliexdev/openWorkout#12]
In the preparation screen it is very difficult to know what comes next. It is written on top, but one can neither see the time, nor the required repetitions. It might be useful to use the space below the video to put it in large letters. E.g.  Squat (30 s) or Squat (20x).

**Comment by oliexdev** [comment]
True it might also be helpful to have always a pause button

**Comment by oliexdev** [comment]
I implemented a pause/resume function and show the time/rep and the name of the workout item during the preparation time.
