### ISSUE TITLE
Crunch vs. sit-up

### ISSUE THREAD

**Issue by jorgman1** [oliexdev/openWorkout#14]
To my understanding, there is a difference between crunches and sit-ups. In a sit-up you go all the way up to the knees, whereas in a crunch you only lift your shoulder.

The video and the description of the crunches corresponds more to sit-ups. Maybe, you could have both exercises.

**Comment by oliexdev** [comment]
I am not a workout expert and sure more workouts are better. 3D rendering the exercises are quite time consumption as I am not an 3D model expert. On my todo list is to write a simple guide how to render a workout video with Blender, so more people can do it on their own. These new model can be uploaded via PR on GitHub were they can be downloaded in the app.

**Comment by oliexdev** [comment]
I added a simple 3D tutorial in the wiki
