### ISSUE TITLE
Add counter for repetitions

### ISSUE THREAD

**Issue by jorgman1** [oliexdev/openWorkout#15]
It would be nice, if one could set a frequency for the repetitions and to hear a sound. That way, one would not need to touch the screen.

**Comment by oliexdev** [comment]
I guess I don't understand what you mean. Do you want to set a time for one repetition?

**Comment by jorgman1** [comment]
Exactly. I would find it useful if you did not have to press the continue button after each exercise. For it to work, one would need to set a repetition time and during the workout, you would need to hear a beep for each repetition or a counter.

But it is only an idea.

**Comment by oliexdev** [comment]
How fast you are in one repetition is highly depend on the person, doesn't it? If you don't want to click the next exercise you can switch to the time mode.

**Comment by jorgman1** [comment]
Yes, the repetition speed is different for all people. That is why you would need a field to define the repetition time.
