### ISSUE TITLE
[Improvement] Dark AMOLED mode

### ISSUE THREAD

**Issue by ebanDev** [oliexdev/openWorkout#18]
Hi, first of all thank you for the great software that is openWorkout !

I think it could be really cool if a Dark AMOLED mode was added to openWorkout...

**Comment by oliexdev** [comment]
what is Dark AMOLED? You can enable the dark mode in the settings.

**Comment by ebanDev** [comment]
Sorry for the delay in my answer, by "Dark AMOLED" I mean dark mode with a black background not gray
