### ISSUE TITLE
(Small screens vertical mode)-> edit exercise -> Time mode switch not visable

### ISSUE THREAD

**Issue by senpl** [oliexdev/openWorkout#19]
On my small resolution phone (Huawei P8 lite) adding exercise shows time mode that is not visible. Also better description what time mode is would be nice.

**Comment by senpl** [comment]
if time mode means static exercise than probably this field should be named static exercise.

**Comment by oliexdev** [comment]
Thanks, I moved the switches to the left side.

What does you understand with static exercise? I want to say with "time mode" that you can configure a time if you enable it otherwise you can set x repetitions of an exercise.
