### ISSUE TITLE
Voice indication

### ISSUE THREAD

**Issue by leogbar** [oliexdev/openWorkout#2]
Your app is very good, I actually use feeel to train 7' routine, but not is editable. Feeel have a great implementation of indication with voice of the actually and next exercise and a countdown from last 5 seconds, can you implement this in your app?

**Comment by oliexdev** [comment]
probably yes but the computer generated voice for the exercise sound a bit off. The last 3 seconds are indicated with a different sound, isn't that enough?

**Comment by leogbar** [comment]
May be you right, but when I train hiit 7' workout stay away from the phone, and can hear the name of the exercise can be usefull, I actually use a combination of feeel (7' workout) from Google store and intervaly to another workouts like stationary bike hiit, last one indicated with a different sound but only I stay in bike

El 21 de octubre de 2020 14:55:19 UTC, OliE <notifications@github.com> escribió:
>probably yes but the computer generated voice for the exercise sound a bit off. The last 3 seconds are indicated with a different sound, isn't that enough?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/oliexdev/openWorkout/issues/2#issuecomment-713636589
-- 
Leonardo Barenghi

**Comment by jorgman1** [comment]
What about Common Voice from Mozilla? Or is it overkill?

**Comment by oliexdev** [comment]
maybe an option is a good idea to enable/disable the voice indication. I already have the Google voice implemented for the "half time" voice indication.

**Comment by oliexdev** [comment]
done

**Comment by leogbar** [comment]
Thanks!!!
