### ISSUE TITLE
Move code base into Kotlin

### ISSUE THREAD

**Issue by senpl** [oliexdev/openWorkout#20]
Current official android language is Kotlin. Change to Kotlin not only simpifies code but also make newest APIs avaliable. Change is not hard and could be done easly from IDE.

**Comment by oliexdev** [comment]
Currently I am more into Java than in Kotlin. Maybe I will change it in the future but for now I want to stick with Java. 
If some API use Kotlin you can still use it in Java they are compatible, so I see no problem here.
