### ISSUE TITLE
Cannot import custom file

### ISSUE THREAD

**Issue by marcown** [oliexdev/openWorkout#25]
[database_1.zip](https://github.com/oliexdev/openWorkout/files/5558371/database_1.zip)

Hey,

it is not possible to import any custom training files (see above). I exported a training, extracted the database.json, customized it und zipped it again. When I want to import it the following error occurs:

.... is not a valid training package

**Comment by clavelc** [comment]
Hi

I'm having the same problem. It will accept the original zip file only, but I cannot modify it. I'm looking at permissions but it doesn't appear to be the reason why

**Comment by oliexdev** [comment]
thanks should be fixed.

**Comment by marcown** [comment]
@oliexdev is there away to directly install the newest git version? 

thanks

**Comment by oliexdev** [comment]
No

Markus Patzold <notifications@github.com> schrieb am Mo., 23. Nov. 2020,
18:13:

**Comment by marcown** [comment]
ok, do you know when you have time to push a new release?

thanks for the work
