### ISSUE TITLE
Enhancement: Sound of rests

### ISSUE THREAD

**Issue by leogbar** [oliexdev/openWorkout#28]
An importante improve me be include sounds or spoken messages in breaks, is you can see the phone during work out.

**Comment by oliexdev** [comment]
Sorry, I don't really understand what your enhancement is? What should be spoken in the breaks? Did you enable the voice indications in the settings already?

**Comment by leogbar** [comment]
Sorry for the time to respond, yes is about the should be spoken in the
breaks, half time and last second to start de workout
