### ISSUE TITLE
Bug: Last workout item skip

### ISSUE THREAD

**Issue by leogbar** [oliexdev/openWorkout#29]
**Describe the bug**
If in the last work put 0 work and 300 s of rest skip the item.

**To Reproduce**
1. Create a example training with some's workouts and include in the last workout 0 s of work and 300 s o any time, this is skip, I use to an extra rest without resistance on static bike for example, or coldwork

**Comment by oliexdev** [comment]
I don't see a problem here? If you set the workout time to 0s then it is of course instantly finished!? If don't want it set a time or disable the time mode, so you have to click to the next workout.

**Comment by leogbar** [comment]
Sorry again fo the time to respond, may be isn't a bug, i use anothers
programs to train and and the habit of use led me to not fully understand
how your app works. I was able to fix it by doing other settings. your app
has become my main tool, as well as openScale, thanks for the work you do.
