### ISSUE TITLE
Rename time mode to static exercise 

### ISSUE THREAD

**Issue by senpl** [oliexdev/openWorkout#31]
Currently used name "time mode" is not clear and commonly used. Static exercise is much easier to use and understanding. sure you could use own names and add tooltips to make users understand fields, but this seems like bed design. it violates "do not make mi think" principle as well .

**Comment by oliexdev** [comment]
First of all I am not an fitness expert but doesn't static exercise mean that you don't move during the workout? For example during a plank?
So the "time" mode should only indicate if a timer is running down or if you can set some repetitions and you have to manually click the next button if your are finished.

**Comment by senpl** [comment]
Name is just a name, It could be named "time counting" or "Finish after time" . Time mode is just name that is not descriptive enough and users are usually confused without tooltip or description.

**Comment by oliexdev** [comment]
For now I want to stick with time mode but other suggestions are welcome.
