### ISSUE TITLE
Allow backup of user data

### ISSUE THREAD

**Issue by senpl** [oliexdev/openWorkout#38]
If this is just adding parametrs than maybe it is worth to give to users.
https://developer.android.com/guide/topics/data/autobackup

**Comment by oliexdev** [comment]
It is automatically enabled:

> Apps that target Android 6.0 (API level 23) or higher automatically participate in Auto Backup. In your app manifest file, set the boolean value android:allowBackup to enable or disable backup. The default value is true but to make your intentions clear, we recommend explicitly setting the attribute in your manifest as shown below:
