### ISSUE TITLE
Days counter does not update in home

### ISSUE THREAD

**Issue by visika** [oliexdev/openWorkout#40]
**Describe the bug**
When choosing a training from the list with the mountain icon, the progress bar and the counter on the right refer to the last training done, not the one on the list.

**To Reproduce**
1. Open the app
2. You should have a training at a different day from the others
3. Pick another training from the list

**Expected behavior**
The progress bar and the counter should refresh when picking a item from the list.

**Additional context**
The meter and the counter actually get updated for the current training if you press start and go back.

**Comment by oliexdev** [comment]
should be fixed
