### ISSUE TITLE
Notifications don't work if app is in background

### ISSUE THREAD

**Issue by Blue-Blue-Christmas** [oliexdev/openWorkout#5]
I set a reminder, but noticed that the app didn't send the notification well after the time I set.
It only sent the notification once I went into the app. As an experiment, I added a reminder then exited the app while keeping it open. Same thing. So it appears the app has to be running in the foreground at the time the reminder's set for in order to work.

**Comment by oliexdev** [comment]
Might be a bug need to test it more but if the app is in the background the time is not exact due the Android shedule system. Which Android version do you using?

**Comment by Blue-Blue-Christmas** [comment]
I'm using Android Version 10.

-------- Original Message --------

**Comment by oliexdev** [comment]
I tested it here in my Android version 10 and it works. Which smartphone do you have? Do you have some energy optimizer on?

**Comment by Blue-Blue-Christmas** [comment]
i have a Moto e.
I do have battery saver on, i didn't know it would do that.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Blue-Blue-Christmas** [comment]
Just tried it again without the battery saver and it worked. :)

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by oliexdev** [comment]
awesome.
