### ISSUE TITLE
Preparation and break time are counter intuitive

### ISSUE THREAD

**Issue by jorgman1** [oliexdev/openWorkout#6]
When editing routines one can set the preparation and the break time. In the training overview you see then

[...] - 5s preparation - Jumping Jack 30s work duration - 30s break - [...]

However, the 30 s break does not take place after the exercise, but before. Could you change that behaviour, or at least put the break before the preparation?

**Comment by oliexdev** [comment]
I guess I don't understand you. The break is after the workout/exercise which is correct. Why should the break before the preparation?

**Comment by jorgman1** [comment]
For example this training:

![Screenshot_1](https://user-images.githubusercontent.com/48908520/96755099-8cba1f80-13d2-11eb-8358-96ba6e60e0f2.png)

When I see this screen, I expect the following behaviour:
5 s preparation - Crunches - 25 s break - 5 s prep - Push ups - 50 s break - 5 s prep. - Crunches

However, it behaves this way:
5 s prep - Crunches - 50 s break - 5 s prep - Push ups - 25 s break - 5 s prep - Crunches

I.e. it puts the break that was defined with the push ups not after the push ups, but before. And in the overview screen it is displayed afterwards.

**Comment by oliexdev** [comment]
now I understand thanks for your explanation. Should be fixed.
